In [87]:
import pandas as pd

# Load CNBC news data
cnbc_df = pd.read_csv("../data/raw/headline_data/cnbc_headlines.csv")
cnbc_df.head(10)

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,NaN,NaN,NaN
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."
5,Wall Street delivered the 'kind of pullback I'...,"7:36 PM ET Thu, 16 July 2020","""Look for the stocks of high-quality companies..."
6,Cramer's lightning round: I would just stay lo...,"7:23 PM ET Thu, 16 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
7,Acorns CEO: Parents can turn $5 into five figu...,"8:03 PM ET Thu, 16 July 2020","Investing $5 per day can compound to $70,000 b..."
8,Dividend cuts may mean rethinking your retirem...,"8:54 AM ET Thu, 16 July 2020",Hundreds of companies have cut or suspended th...
9,NaN,NaN,NaN

In [88]:
print(f"CNBC dataset shape: {cnbc_df.shape}")
print(f"CNBC dataset columns: {cnbc_df.columns.tolist()}")
print(f"CNBC dataset missing values:\n{cnbc_df.isnull().sum()}")

CNBC dataset shape: (3080, 3)
CNBC dataset columns: ['Headlines', 'Time', 'Description']
CNBC dataset missing values:
Headlines      280
Time           280
Description    280
dtype: int64

In [89]:
# Drop NaN from CNBC dataset
cnbc_df.dropna(inplace=True)
cnbc_df.head(10)

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."
5,Wall Street delivered the 'kind of pullback I'...,"7:36 PM ET Thu, 16 July 2020","""Look for the stocks of high-quality companies..."
6,Cramer's lightning round: I would just stay lo...,"7:23 PM ET Thu, 16 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
7,Acorns CEO: Parents can turn $5 into five figu...,"8:03 PM ET Thu, 16 July 2020","Investing $5 per day can compound to $70,000 b..."
8,Dividend cuts may mean rethinking your retirem...,"8:54 AM ET Thu, 16 July 2020",Hundreds of companies have cut or suspended th...
10,StockX has authenticated 1 million Jordan snea...,"8:25 PM ET Wed, 15 July 2020","""We've been able to capture these cultural mom..."
11,Biohaven Pharmaceuticals lands Khloe Kardashia...,"7:51 PM ET Wed, 15 July 2020",Biohaven CEO Vlad Coric said the company broug...

In [90]:
print(f"CNBC dataset shape: {cnbc_df.shape}")
print(f"CNBC dataset columns: {cnbc_df.columns.tolist()}")
print(f"CNBC dataset missing values:\n{cnbc_df.isnull().sum()}")

CNBC dataset shape: (2800, 3)
CNBC dataset columns: ['Headlines', 'Time', 'Description']
CNBC dataset missing values:
Headlines      0
Time           0
Description    0
dtype: int64

In [91]:
# Load Guardian news data
guardian_df = pd.read_csv("../data/raw/headline_data/guardian_headlines.csv")
guardian_df.head(10)

        Time                                          Headlines
0  18-Jul-20   Johnson is asking Santa for a Christmas recovery
1  18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2  18-Jul-20  Five key areas Sunak must tackle to serve up e...
3  18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  18-Jul-20  The Week in Patriarchy  \n\n\n  Bacardi's 'lad...
5  18-Jul-20  English councils call for smoking ban outside ...
6  18-Jul-20              Can Tesla justify a $300bn valuation?
7  18-Jul-20  Empty city centres: 'I’m not sure it will ever...
8  18-Jul-20  Democratising finance for all? An investment a...
9  18-Jul-20  Homebuyer loses £300,000 to fraudsters – but g...

In [92]:
print(f"Guardian dataset shape: {guardian_df.shape}")  
print(f"Guardian dataset columns: {guardian_df.columns.tolist()}")
print(f"Guardian dataset missing values:\n{guardian_df.isnull().sum()}")

Guardian dataset shape: (17800, 2)
Guardian dataset columns: ['Time', 'Headlines']
Guardian dataset missing values:
Time         0
Headlines    0
dtype: int64

In [93]:
# Load Reuters news data
reuters_df = pd.read_csv("../data/raw/headline_data/reuters_headlines.csv")
reuters_df.head(10)

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...
5,Wall Street Week Ahead: Fund managers navigate...,Jul 17 2020,Investors are searching for bargains in the wo...
6,Take Five: Hoping for that V-shape in earnings,Jul 17 2020,We knew Q2 earnings would be dire but the hope...
7,Evictions nearly back to pre-pandemic levels i...,Jul 17 2020,Landlords in some areas of the United States a...
8,Google bans ads on coronavirus conspiracy theo...,Jul 17 2020,Alphabet Inc's Google said on Friday it would ...
9,"Flight to suburbs boosts U.S. homebuilding, bu...",Jul 17 2020,U.S. homebuilding increased in June by the mos...

In [94]:
print(f"Reuters dataset shape: {reuters_df.shape}")
print(f"Reuters dataset columns: {reuters_df.columns.tolist()}")
print(f"Reuters dataset missing values:\n{reuters_df.isnull().sum()}")

Reuters dataset shape: (32770, 3)
Reuters dataset columns: ['Headlines', 'Time', 'Description']
Reuters dataset missing values:
Headlines      0
Time           0
Description    0
dtype: int64

### Checking time format

In [95]:
print("-------CNBC Time Column Sample-------")
print(cnbc_df["Time"].head())
print("-------Guardian Time Column Sample-------")
print(guardian_df["Time"].head())
print("-------Reuters Time Column Sample-------")
print(reuters_df["Time"].head())

-------CNBC Time Column Sample-------
0     7:51  PM ET Fri, 17 July 2020
1     7:33  PM ET Fri, 17 July 2020
3     7:25  PM ET Fri, 17 July 2020
4     4:24  PM ET Fri, 17 July 2020
5     7:36  PM ET Thu, 16 July 2020
Name: Time, dtype: str
-------Guardian Time Column Sample-------
0    18-Jul-20
1    18-Jul-20
2    18-Jul-20
3    18-Jul-20
4    18-Jul-20
Name: Time, dtype: str
-------Reuters Time Column Sample-------
0    Jul 18 2020
1    Jul 18 2020
2    Jul 18 2020
3    Jul 18 2020
4    Jul 17 2020
Name: Time, dtype: str

#### Modifying time formats

In [96]:
cnbc_df["Date"] = pd.to_datetime(
    cnbc_df["Time"]
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.replace(" ET ", " ", regex=False),
    format="mixed"
).dt.strftime("%Y-%m-%d")
print("-------CNBC Date Column Sample-------")
print(cnbc_df["Date"].head())

-------CNBC Date Column Sample-------
0    2020-07-17
1    2020-07-17
3    2020-07-17
4    2020-07-17
5    2020-07-16
Name: Date, dtype: str

In [115]:
guardian_df["Date"] = (
    pd.to_datetime(guardian_df["Time"])
    .dt.strftime("%Y-%m-%d")
)
print("-------Guardian Date Column Sample-------")
print(guardian_df["Date"].head())

-------Guardian Date Column Sample-------
0    2020-07-18
1    2020-07-18
2    2020-07-18
3    2020-07-18
4    2020-07-18
Name: Date, dtype: str

/var/folders/7p/d217p6713972xw562cx4xj880000gp/T/ipykernel_16998/854668322.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(guardian_df["Time"])

In [116]:
guardian_df.isnull().sum()

Time         0
Headlines    0
Date         0
Source       0
dtype: int64

In [124]:
guardian_df[guardian_df["Time"].str.strip().str.match(r"^[A-Za-z]{3}-\d{2}$", na=False)]

,Time,Headlines,Date,Source
13920,Jul-18,The shifting patterns of English \n\n\n May ...,1-07-18,guardian
13921,Jul-18,Dealers shift down a gear as Brexit takes the ...,1-07-18,guardian
13922,Jul-18,"Sun over Blackpool and Scarborough, but dark d...",1-07-18,guardian
13923,Jul-18,Lettuce crops flop as Britain wilts in hot wea...,1-07-18,guardian
13924,Jul-18,Go-ahead given for merger of Tata Steel and Th...,1-07-18,guardian
13925,Jul-18,"How I spend it ‘I’m a billionaire, but I'm no...",1-07-18,guardian
13926,Jul-18,MPs back plan for ombudsman to resolve new hom...,1-07-18,guardian
13927,Jul-18,Coalition’s tax strategy at odds with OECD and...,1-07-18,guardian
13928,Jul-18,General Motors warns Trump: tariffs could lead...,1-07-18,guardian
13929,Jul-18,Canada hits US with retaliatory tariffs: 'We w...,1-07-18,guardian
13930,Jul-18,Virgin airlines says it will no longer help to...,1-07-18,guardian
13931,Jul-18,Pubs and retailers hope for end to CO2 shortag...,1-07-18,guardian
13932,Jul-18,Estonian president delights in country’s high ...,1-07-18,guardian
13933,Jul-18,PwC hangs up on landlines in shift to ‘mobile ...,1-07-18,guardian
13934,Jul-18,Lloyd's of London's first female CEO Inga Beal...,1-07-18,guardian
13935,Jul-18,Brief letters Morris Minor mishaps and meerka...,1-07-18,guardian
13936,Jul-18,Sir Philip Green’s firm fails in attempt to bl...,1-07-18,guardian
13937,Jul-18,Faang-tastic five: can US tech giants continue...,1-07-18,guardian
13938,Jul-18,"Pretty, peppery, perfect for summer: heatwave ...",1-07-18,guardian
13939,Jul-18,Oxford buses turn to Uber-style apps in on-dem...,1-07-18,guardian
15680,Apr-18,GKN will be stripped and sold for parts by gho...,1-04-18,guardian
15681,Apr-18,Trump again attacks Amazon's postal service de...,1-04-18,guardian
15682,Apr-18,Restaurant chains still force waiting staff to...,1-04-18,guardian
15683,Apr-18,Co-op to switch own-brand water to 50% recycle...,1-04-18,guardian
15684,Apr-18,Ex-Uber boss was paid $4m by investor that acq...,1-04-18,guardian
15685,Apr-18,How I spend it ‘I am 24 and live with my pare...,1-04-18,guardian
15686,Apr-18,"From car insurance to banking, a new digital a...",1-04-18,guardian
15687,Apr-18,Data expert battles Nationwide after phantom w...,1-04-18,guardian
15688,Apr-18,Walmart reported to be in talks to buy health ...,1-04-18,guardian
15689,Apr-18,Brief letters Signed off school with Beatlemania,1-04-18,guardian
15690,Apr-18,Declaring war on Cosmo? It feels like we're ba...,1-04-18,guardian
15691,Apr-18,Baobab fruit takes off as a ‘superfood’ with s...,1-04-18,guardian
15692,Apr-18,Global mergers and acquisitions reach record h...,1-04-18,guardian
15693,Apr-18,Cosmopolitan drawn into US culture wars as con...,1-04-18,guardian
15694,Apr-18,The Guardian's Audio Long Reads Perfect prams...,1-04-18,guardian
15695,Apr-18,‘Homebase is the most disastrous retail acquis...,1-04-18,guardian
15696,Apr-18,"Cathay Pacific completes two-leg journey, lett...",1-04-18,guardian
15697,Apr-18,Brexit means eggs sit: Ferrero warns of stale ...,1-04-18,guardian
15698,Apr-18,Corbyn: interests of City speculators put abov...,1-04-18,guardian
15699,Apr-18,Country diary Country diary: my crash course ...,1-04-18,guardian

In [117]:
reuters_df["Date"] = pd.to_datetime(
    reuters_df["Time"],
    format="%b %d %Y"
)
print("-------Reuters Date Column Sample-------")
print(reuters_df["Date"].head())

-------Reuters Date Column Sample-------
0   2020-07-18
1   2020-07-18
2   2020-07-18
3   2020-07-18
4   2020-07-17
Name: Date, dtype: datetime64[us]

## Combining all dataframes

In [118]:
for df, source in [
    (cnbc_df, "cnbc"),
    (guardian_df, "guardian"),
    (reuters_df, "reuters"),
]:
    df["Source"] = source

combined_df = pd.concat(
    [
        cnbc_df[["Headlines", "Date", "Source"]],
        guardian_df[["Headlines", "Date", "Source"]],
        reuters_df[["Headlines", "Date", "Source"]],
    ],
    ignore_index=True,
)

combined_df["Date"] = pd.to_datetime(combined_df["Date"], errors="coerce")

In [119]:
combined_df

                                               Headlines       Date   Source
0      Jim Cramer: A better way to invest in the Covi... 2020-07-17     cnbc
1         Cramer's lightning round: I would own Teradyne 2020-07-17     cnbc
2      Cramer's week ahead: Big week for earnings, ev... 2020-07-17     cnbc
3      IQ Capital CEO Keith Bliss says tech and healt... 2020-07-17     cnbc
4      Wall Street delivered the 'kind of pullback I'... 2020-07-16     cnbc
...                                                  ...        ...      ...
53365  Malaysia says never hired British data firm at... 2018-03-20  reuters
53366  Prosecutors search Volkswagen headquarters in ... 2018-03-20  reuters
53367   McDonald's sets greenhouse gas reduction targets 2018-03-20  reuters
53368  Pratt & Whitney to deliver spare A320neo engin... 2018-03-20  reuters
53369  UK will always consider ways to improve data l... 2018-03-20  reuters

[53370 rows x 3 columns]

In [120]:
# Save the combined DataFrame to a new CSV file
combined_df.to_csv("../data/processed/news_combined.csv", index=False)

# EDA for combined dataset

In [121]:
news_df = pd.read_csv("../data/processed/news_combined.csv")
news_df.head()

                                           Headlines        Date Source
0  Jim Cramer: A better way to invest in the Covi...  2020-07-17   cnbc
1     Cramer's lightning round: I would own Teradyne  2020-07-17   cnbc
2  Cramer's week ahead: Big week for earnings, ev...  2020-07-17   cnbc
3  IQ Capital CEO Keith Bliss says tech and healt...  2020-07-17   cnbc
4  Wall Street delivered the 'kind of pullback I'...  2020-07-16   cnbc

In [122]:
print(f"Shape of news_df: {news_df.shape}")
print(f"Columns in news_df: {news_df.columns.tolist()}")
print(f"Missing values in news_df:\n{news_df.isnull().sum()}")

Shape of news_df: (53370, 3)
Columns in news_df: ['Headlines', 'Date', 'Source']
Missing values in news_df:
Headlines     0
Date         40
Source        0
dtype: int64

In [123]:
news_df[news_df.isnull().any(axis=1)]

                                               Headlines Date    Source
16720  The shifting patterns of English  \n\n\n  May ...  NaN  guardian
16721  Dealers shift down a gear as Brexit takes the ...  NaN  guardian
16722  Sun over Blackpool and Scarborough, but dark d...  NaN  guardian
16723  Lettuce crops flop as Britain wilts in hot wea...  NaN  guardian
16724  Go-ahead given for merger of Tata Steel and Th...  NaN  guardian
16725  How I spend it  ‘I’m a billionaire, but I'm no...  NaN  guardian
16726  MPs back plan for ombudsman to resolve new hom...  NaN  guardian
16727  Coalition’s tax strategy at odds with OECD and...  NaN  guardian
16728  General Motors warns Trump: tariffs could lead...  NaN  guardian
16729  Canada hits US with retaliatory tariffs: 'We w...  NaN  guardian
16730  Virgin airlines says it will no longer help to...  NaN  guardian
16731  Pubs and retailers hope for end to CO2 shortag...  NaN  guardian
16732  Estonian president delights in country’s high ...  NaN  guardian
16733  PwC hangs up on landlines in shift to ‘mobile ...  NaN  guardian
16734  Lloyd's of London's first female CEO Inga Beal...  NaN  guardian
16735  Brief letters  Morris Minor mishaps and meerka...  NaN  guardian
16736  Sir Philip Green’s firm fails in attempt to bl...  NaN  guardian
16737  Faang-tastic five: can US tech giants continue...  NaN  guardian
16738  Pretty, peppery, perfect for summer: heatwave ...  NaN  guardian
16739  Oxford buses turn to Uber-style apps in on-dem...  NaN  guardian
18480  GKN will be stripped and sold for parts by gho...  NaN  guardian
18481  Trump again attacks Amazon's postal service de...  NaN  guardian
18482  Restaurant chains still force waiting staff to...  NaN  guardian
18483  Co-op to switch own-brand water to 50% recycle...  NaN  guardian
18484  Ex-Uber boss was paid $4m by investor that acq...  NaN  guardian
18485  How I spend it  ‘I am 24 and live with my pare...  NaN  guardian
18486  From car insurance to banking, a new digital a...  NaN  guardian
18487  Data expert battles Nationwide after phantom w...  NaN  guardian
18488  Walmart reported to be in talks to buy health ...  NaN  guardian
18489  Brief letters  Signed off school with Beatlemania  NaN  guardian
18490  Declaring war on Cosmo? It feels like we're ba...  NaN  guardian
18491  Baobab fruit takes off as a ‘superfood’ with s...  NaN  guardian
18492  Global mergers and acquisitions reach record h...  NaN  guardian
18493  Cosmopolitan drawn into US culture wars as con...  NaN  guardian
18494  The Guardian's Audio Long Reads  Perfect prams...  NaN  guardian
18495  ‘Homebase is the most disastrous retail acquis...  NaN  guardian
18496  Cathay Pacific completes two-leg journey, lett...  NaN  guardian
18497  Brexit means eggs sit: Ferrero warns of stale ...  NaN  guardian
18498  Corbyn: interests of City speculators put abov...  NaN  guardian
18499  Country diary  Country diary: my crash course ...  NaN  guardian

In [125]:
# Drop those rows with NaN in Date
news_df.dropna(subset=["Date"], inplace=True)
news_df.isnull().sum()

Headlines    0
Date         0
Source       0
dtype: int64

In [128]:
print(f"Shape of news_df = {news_df.shape}")
print(f"Source value counts:")
print(news_df["Source"].value_counts())
print(f"Minimum Date: {news_df['Date'].min()}")
print(f"Maximum Date: {news_df['Date'].max()}")

Shape of news_df = (53330, 3)
Source value counts:
Source
reuters     32770
guardian    17760
cnbc         2800
Name: count, dtype: int64
Minimum Date: 2017-12-17
Maximum Date: 2020-07-18

In [129]:
news_df = news_df.drop_duplicates()
news_df.shape

(53243, 3)

In [130]:
# Save news_df as a csv file in data/processed directory
news_df.to_csv("../data/processed/news_clean.csv", index=False)